//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCADTools.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCADTools.Management.LocalData", typeof(LocalData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made a mistake when changing data. This is the official description:.
        /// </summary>
        internal static string DataErrorMessage {
            get {
                return ResourceManager.GetString("DataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        internal static string DataErrorTitle {
            get {
                return ResourceManager.GetString("DataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Detail.
        /// </summary>
        internal static string EditDetailTitle {
            get {
                return ResourceManager.GetString("EditDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        internal static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logogram.
        /// </summary>
        internal static string EmployerShort {
            get {
                return ResourceManager.GetString("EmployerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is empty.
        /// </summary>
        internal static string ErrorEmptyContent {
            get {
                return ResourceManager.GetString("ErrorEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty.
        /// </summary>
        internal static string ErrorEmptyName {
            get {
                return ResourceManager.GetString("ErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectnumber cannot be empty.
        /// </summary>
        internal static string ErrorEmptyProjectnumber {
            get {
                return ResourceManager.GetString("ErrorEmptyProjectnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a number.
        /// </summary>
        internal static string ErrorNoNumber {
            get {
                return ResourceManager.GetString("ErrorNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectnumber is already in use.
        /// </summary>
        internal static string ErrorUsedProjectnumber {
            get {
                return ResourceManager.GetString("ErrorUsedProjectnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ModifyAdd {
            get {
                return ResourceManager.GetString("ModifyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ModifyEdit {
            get {
                return ResourceManager.GetString("ModifyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ModifySubmit {
            get {
                return ResourceManager.GetString("ModifySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection to the database possible. Check the settings and make sure the database server is running. Please skip the following error message..
        /// </summary>
        internal static string NoConnectionText {
            get {
                return ResourceManager.GetString("NoConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Database Connection.
        /// </summary>
        internal static string NoConnectionTitle {
            get {
                return ResourceManager.GetString("NoConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is still a plot running.
        /// </summary>
        internal static string PlotRunningText {
            get {
                return ResourceManager.GetString("PlotRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Running.
        /// </summary>
        internal static string PlotRunningTitle {
            get {
                return ResourceManager.GetString("PlotRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout is being created..
        /// </summary>
        internal static string PNGPlotCreateLayout {
            get {
                return ResourceManager.GetString("PNGPlotCreateLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot is being initialized..
        /// </summary>
        internal static string PNGPlotInitialize {
            get {
                return ResourceManager.GetString("PNGPlotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Preview is being plotted..
        /// </summary>
        internal static string PNGPlotText {
            get {
                return ResourceManager.GetString("PNGPlotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotting PNG.
        /// </summary>
        internal static string PNGPlotTitle {
            get {
                return ResourceManager.GetString("PNGPlotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for plot being finalized..
        /// </summary>
        internal static string PNGPlotWaiting {
            get {
                return ResourceManager.GetString("PNGPlotWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectnumber.
        /// </summary>
        internal static string Projectnumber {
            get {
                return ResourceManager.GetString("Projectnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
    }
}
