//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCADTools.Management {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalData() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCADTools.Management.LocalData", typeof(LocalData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You made a mistake when changing data. This is the official description: ähnelt.
        /// </summary>
        internal static string DataErrorMessage {
            get {
                return ResourceManager.GetString("DataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input Error ähnelt.
        /// </summary>
        internal static string DataErrorTitle {
            get {
                return ResourceManager.GetString("DataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Detail ähnelt.
        /// </summary>
        internal static string EditDetailTitle {
            get {
                return ResourceManager.GetString("EditDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Employer ähnelt.
        /// </summary>
        internal static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logogram ähnelt.
        /// </summary>
        internal static string EmployerShort {
            get {
                return ResourceManager.GetString("EmployerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content is empty ähnelt.
        /// </summary>
        internal static string ErrorEmptyContent {
            get {
                return ResourceManager.GetString("ErrorEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name is empty ähnelt.
        /// </summary>
        internal static string ErrorEmptyName {
            get {
                return ResourceManager.GetString("ErrorEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projectnumber cannot be empty ähnelt.
        /// </summary>
        internal static string ErrorEmptyProjectnumber {
            get {
                return ResourceManager.GetString("ErrorEmptyProjectnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die That is not a number ähnelt.
        /// </summary>
        internal static string ErrorNoNumber {
            get {
                return ResourceManager.GetString("ErrorNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projectnumber is already in use ähnelt.
        /// </summary>
        internal static string ErrorUsedProjectnumber {
            get {
                return ResourceManager.GetString("ErrorUsedProjectnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string ModifyAdd {
            get {
                return ResourceManager.GetString("ModifyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string ModifyEdit {
            get {
                return ResourceManager.GetString("ModifyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        internal static string ModifySubmit {
            get {
                return ResourceManager.GetString("ModifySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no connection to the database possible. Check the settings and make sure the database server is running. Please skip the following error message. ähnelt.
        /// </summary>
        internal static string NoConnectionText {
            get {
                return ResourceManager.GetString("NoConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Database Connection ähnelt.
        /// </summary>
        internal static string NoConnectionTitle {
            get {
                return ResourceManager.GetString("NoConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is still a plot running ähnelt.
        /// </summary>
        internal static string PlotRunningText {
            get {
                return ResourceManager.GetString("PlotRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plot Running ähnelt.
        /// </summary>
        internal static string PlotRunningTitle {
            get {
                return ResourceManager.GetString("PlotRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layout is being created. ähnelt.
        /// </summary>
        internal static string PNGPlotCreateLayout {
            get {
                return ResourceManager.GetString("PNGPlotCreateLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plot is being initialized. ähnelt.
        /// </summary>
        internal static string PNGPlotInitialize {
            get {
                return ResourceManager.GetString("PNGPlotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PNG Preview is being plotted. ähnelt.
        /// </summary>
        internal static string PNGPlotText {
            get {
                return ResourceManager.GetString("PNGPlotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plotting PNG ähnelt.
        /// </summary>
        internal static string PNGPlotTitle {
            get {
                return ResourceManager.GetString("PNGPlotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for plot being finalized. ähnelt.
        /// </summary>
        internal static string PNGPlotWaiting {
            get {
                return ResourceManager.GetString("PNGPlotWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projectnumber ähnelt.
        /// </summary>
        internal static string Projectnumber {
            get {
                return ResourceManager.GetString("Projectnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save changes? ähnelt.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes ähnelt.
        /// </summary>
        internal static string SaveChangesTitle {
            get {
                return ResourceManager.GetString("SaveChangesTitle", resourceCulture);
            }
        }
    }
}
