//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCADTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlConnectionLogin {
            get {
                return ((string)(this["SqlConnectionLogin"]));
            }
            set {
                this["SqlConnectionLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlConnectionPassword {
            get {
                return ((string)(this["SqlConnectionPassword"]));
            }
            set {
                this["SqlConnectionPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string SqlConnectionPort {
            get {
                return ((string)(this["SqlConnectionPort"]));
            }
            set {
                this["SqlConnectionPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string SqlConnectionTimeout {
            get {
                return ((string)(this["SqlConnectionTimeout"]));
            }
            set {
                this["SqlConnectionTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AutoCAD")]
        public string SqlConnectionDatabase {
            get {
                return ((string)(this["SqlConnectionDatabase"]));
            }
            set {
                this["SqlConnectionDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiagonalBracingDescriptionBlack {
            get {
                return ((bool)(this["DiagonalBracingDescriptionBlack"]));
            }
            set {
                this["DiagonalBracingDescriptionBlack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Konica")]
        public string DefaultPrinterA4 {
            get {
                return ((string)(this["DefaultPrinterA4"]));
            }
            set {
                this["DefaultPrinterA4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Konica")]
        public string DefaultPrinterA3 {
            get {
                return ((string)(this["DefaultPrinterA3"]));
            }
            set {
                this["DefaultPrinterA3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plotter")]
        public string DefaultPrinterCustom {
            get {
                return ((string)(this["DefaultPrinterCustom"]));
            }
            set {
                this["DefaultPrinterCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plot")]
        public string DefaultLayoutName {
            get {
                return ((string)(this["DefaultLayoutName"]));
            }
            set {
                this["DefaultLayoutName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SERVER_URL")]
        public string SqlConnectionPath {
            get {
                return ((string)(this["SqlConnectionPath"]));
            }
            set {
                this["SqlConnectionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>A0</string>\r\n  <string>A3</string>\r\n  <string>A4</string>\r\n</ArrayOfString" +
            ">")]
        public global::System.Collections.Specialized.StringCollection OrdinaryPaperformats {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrdinaryPaperformats"]));
            }
            set {
                this["OrdinaryPaperformats"] = value;
            }
        }
    }
}
