//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCADTools.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCADTools.Tools.LocalData", typeof(LocalData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string CompressionWoodAngle {
            get {
                return ResourceManager.GetString("CompressionWoodAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompressionWood.
        /// </summary>
        internal static string CompressionWoodBlockPrefix {
            get {
                return ResourceManager.GetString("CompressionWoodBlockPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string CompressionWoodHeight {
            get {
                return ResourceManager.GetString("CompressionWoodHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string CompressionWoodWidth {
            get {
                return ResourceManager.GetString("CompressionWoodWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On changing current drawing unit the current drawing frame will (if existing) be deleted. Continue?.
        /// </summary>
        internal static string DeleteDrawingAreaText {
            get {
                return ResourceManager.GetString("DeleteDrawingAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        internal static string DeleteDrawingAreaTitle {
            get {
                return ResourceManager.GetString("DeleteDrawingAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (first end).
        /// </summary>
        internal static string DiagonalBracingFirstAddition {
            get {
                return ResourceManager.GetString("DiagonalBracingFirstAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify first point.
        /// </summary>
        internal static string DiagonalBracingFirstPoint {
            get {
                return ResourceManager.GetString("DiagonalBracingFirstPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position or description is missing. Continue?.
        /// </summary>
        internal static string DiagonalBracingMissingDescriptionText {
            get {
                return ResourceManager.GetString("DiagonalBracingMissingDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        internal static string DiagonalBracingMissingDescriptionTitle {
            get {
                return ResourceManager.GetString("DiagonalBracingMissingDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify second point.
        /// </summary>
        internal static string DiagonalBracingSecondPoint {
            get {
                return ResourceManager.GetString("DiagonalBracingSecondPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (second end).
        /// </summary>
        internal static string DiagonalBracingSecondsAddition {
            get {
                return ResourceManager.GetString("DiagonalBracingSecondsAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal places.
        /// </summary>
        internal static string DimensionDecimalPlaces {
            get {
                return ResourceManager.GetString("DimensionDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion point.
        /// </summary>
        internal static string DimensionInsertionPoint {
            get {
                return ResourceManager.GetString("DimensionInsertionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference point.
        /// </summary>
        internal static string DimensionReferencePoint {
            get {
                return ResourceManager.GetString("DimensionReferencePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string EmptyDrawingSetting {
            get {
                return ResourceManager.GetString("EmptyDrawingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eave overhang.
        /// </summary>
        internal static string GroundPlanEaveOverhangPrompt {
            get {
                return ResourceManager.GetString("GroundPlanEaveOverhangPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string GroundPlanLengthPrompt {
            get {
                return ResourceManager.GetString("GroundPlanLengthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verge overhang.
        /// </summary>
        internal static string GroundPlanVergeOverhangPrompt {
            get {
                return ResourceManager.GetString("GroundPlanVergeOverhangPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall thickness.
        /// </summary>
        internal static string GroundPlanWallThicknessPrompt {
            get {
                return ResourceManager.GetString("GroundPlanWallThicknessPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string GroundPlanWidthPrompt {
            get {
                return ResourceManager.GetString("GroundPlanWidthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify insertion point.
        /// </summary>
        internal static string InsertionPoint {
            get {
                return ResourceManager.GetString("InsertionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positionnumber.
        /// </summary>
        internal static string PositionnumberPrompt {
            get {
                return ResourceManager.GetString("PositionnumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.10.
        /// </summary>
        internal static string ReinforcingBondDefaultDistance {
            get {
                return ResourceManager.GetString("ReinforcingBondDefaultDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First point at eave.
        /// </summary>
        internal static string ReinforcingBondFirstEave {
            get {
                return ResourceManager.GetString("ReinforcingBondFirstEave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point at ridge (in direction of first eave point).
        /// </summary>
        internal static string ReinforcingBondRidge {
            get {
                return ResourceManager.GetString("ReinforcingBondRidge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second point at eave.
        /// </summary>
        internal static string ReinforcingBondSecondEave {
            get {
                return ResourceManager.GetString("ReinforcingBondSecondEave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1.
        /// </summary>
        internal static string StandardPosition {
            get {
                return ResourceManager.GetString("StandardPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roof: Gangnail-Trusses.
        /// </summary>
        internal static string StandardSegment {
            get {
                return ResourceManager.GetString("StandardSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text.
        /// </summary>
        internal static string TextBorderSelectPrompt {
            get {
                return ResourceManager.GetString("TextBorderSelectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while importing the objects. Contact the developer with the following information: .
        /// </summary>
        internal static string TrussImportErrorText {
            get {
                return ResourceManager.GetString("TrussImportErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TrussImportErrorTitle {
            get {
                return ResourceManager.GetString("TrussImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not found: .
        /// </summary>
        internal static string TrussImportFileNotFoundText {
            get {
                return ResourceManager.GetString("TrussImportFileNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown File.
        /// </summary>
        internal static string TrussImportFileNotFoundTitle {
            get {
                return ResourceManager.GetString("TrussImportFileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify input point.
        /// </summary>
        internal static string TrussImportInputPoint {
            get {
                return ResourceManager.GetString("TrussImportInputPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearings.
        /// </summary>
        internal static string TrussImportSuffixBearings {
            get {
                return ResourceManager.GetString("TrussImportSuffixBearings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracings.
        /// </summary>
        internal static string TrussImportSuffixBracings {
            get {
                return ResourceManager.GetString("TrussImportSuffixBracings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        internal static string TrussImportSuffixDimensions {
            get {
                return ResourceManager.GetString("TrussImportSuffixDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string TrussImportSuffixMembers {
            get {
                return ResourceManager.GetString("TrussImportSuffixMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plates.
        /// </summary>
        internal static string TrussImportSuffixPlates {
            get {
                return ResourceManager.GetString("TrussImportSuffixPlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Whitespace {
            get {
                return ResourceManager.GetString("Whitespace", resourceCulture);
            }
        }
    }
}
