//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCADTools.Tools {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalData() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCADTools.Tools.LocalData", typeof(LocalData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angle ähnelt.
        /// </summary>
        internal static string CompressionWoodAngle {
            get {
                return ResourceManager.GetString("CompressionWoodAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CompressionWood ähnelt.
        /// </summary>
        internal static string CompressionWoodBlockPrefix {
            get {
                return ResourceManager.GetString("CompressionWoodBlockPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        internal static string CompressionWoodHeight {
            get {
                return ResourceManager.GetString("CompressionWoodHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        internal static string CompressionWoodWidth {
            get {
                return ResourceManager.GetString("CompressionWoodWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On changing current drawing unit the current drawing frame will (if existing) be deleted. Continue? ähnelt.
        /// </summary>
        internal static string DeleteDrawingAreaText {
            get {
                return ResourceManager.GetString("DeleteDrawingAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue? ähnelt.
        /// </summary>
        internal static string DeleteDrawingAreaTitle {
            get {
                return ResourceManager.GetString("DeleteDrawingAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decimal places ähnelt.
        /// </summary>
        internal static string DimensionDecimalPlaces {
            get {
                return ResourceManager.GetString("DimensionDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insertion point ähnelt.
        /// </summary>
        internal static string DimensionInsertionPoint {
            get {
                return ResourceManager.GetString("DimensionInsertionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference point ähnelt.
        /// </summary>
        internal static string DimensionReferencePoint {
            get {
                return ResourceManager.GetString("DimensionReferencePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   ähnelt.
        /// </summary>
        internal static string EmptyDrawingSetting {
            get {
                return ResourceManager.GetString("EmptyDrawingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (first end) ähnelt.
        /// </summary>
        internal static string PanicleFirstAddition {
            get {
                return ResourceManager.GetString("PanicleFirstAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify first point ähnelt.
        /// </summary>
        internal static string PanicleFirstPoint {
            get {
                return ResourceManager.GetString("PanicleFirstPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position or description is missing. Continue? ähnelt.
        /// </summary>
        internal static string PanicleMissingDescriptionText {
            get {
                return ResourceManager.GetString("PanicleMissingDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue? ähnelt.
        /// </summary>
        internal static string PanicleMissingDescriptionTitle {
            get {
                return ResourceManager.GetString("PanicleMissingDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify second point ähnelt.
        /// </summary>
        internal static string PanicleSecondPoint {
            get {
                return ResourceManager.GetString("PanicleSecondPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (second end) ähnelt.
        /// </summary>
        internal static string PanicleSecondsAddition {
            get {
                return ResourceManager.GetString("PanicleSecondsAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First point at eave ähnelt.
        /// </summary>
        internal static string ReinforcingBondFirstEave {
            get {
                return ResourceManager.GetString("ReinforcingBondFirstEave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Point at ridge (in direction of first eave point) ähnelt.
        /// </summary>
        internal static string ReinforcingBondRidge {
            get {
                return ResourceManager.GetString("ReinforcingBondRidge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Second point at eave ähnelt.
        /// </summary>
        internal static string ReinforcingBondSecondEave {
            get {
                return ResourceManager.GetString("ReinforcingBondSecondEave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P1 ähnelt.
        /// </summary>
        internal static string StandardPosition {
            get {
                return ResourceManager.GetString("StandardPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roof: Gangnail-Trusses ähnelt.
        /// </summary>
        internal static string StandardSegment {
            get {
                return ResourceManager.GetString("StandardSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while importing the objects. ähnelt.
        /// </summary>
        internal static string TrussImportErrorText {
            get {
                return ResourceManager.GetString("TrussImportErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string TrussImportErrorTitle {
            get {
                return ResourceManager.GetString("TrussImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File was not found ähnelt.
        /// </summary>
        internal static string TrussImportFileNotFoundText {
            get {
                return ResourceManager.GetString("TrussImportFileNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown File ähnelt.
        /// </summary>
        internal static string TrussImportFileNotFoundTitle {
            get {
                return ResourceManager.GetString("TrussImportFileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify input point ähnelt.
        /// </summary>
        internal static string TrussImportInputPoint {
            get {
                return ResourceManager.GetString("TrussImportInputPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearings ähnelt.
        /// </summary>
        internal static string TrussImportSuffixBearings {
            get {
                return ResourceManager.GetString("TrussImportSuffixBearings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bracings ähnelt.
        /// </summary>
        internal static string TrussImportSuffixBracings {
            get {
                return ResourceManager.GetString("TrussImportSuffixBracings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dimensions ähnelt.
        /// </summary>
        internal static string TrussImportSuffixDimensions {
            get {
                return ResourceManager.GetString("TrussImportSuffixDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Members ähnelt.
        /// </summary>
        internal static string TrussImportSuffixMembers {
            get {
                return ResourceManager.GetString("TrussImportSuffixMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plates ähnelt.
        /// </summary>
        internal static string TrussImportSuffixPlates {
            get {
                return ResourceManager.GetString("TrussImportSuffixPlates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   ähnelt.
        /// </summary>
        internal static string Whitespace {
            get {
                return ResourceManager.GetString("Whitespace", resourceCulture);
            }
        }
    }
}
