//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCADTools.PrintLayout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoCADTools.PrintLayout.LocalData", typeof(LocalData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified default printer is not found..
        /// </summary>
        internal static string DefaultPrinterInvalid {
            get {
                return ResourceManager.GetString("DefaultPrinterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while finding the drawing area. Please create a new one and delete the old one if existing..
        /// </summary>
        internal static string DrawingAreaFindErrorMessage {
            get {
                return ResourceManager.GetString("DrawingAreaFindErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Area Error.
        /// </summary>
        internal static string DrawingAreaFindErrorTitle {
            get {
                return ResourceManager.GetString("DrawingAreaFindErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion point.
        /// </summary>
        internal static string DrawingAreaInsertionText {
            get {
                return ResourceManager.GetString("DrawingAreaInsertionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target point.
        /// </summary>
        internal static string DrawingAreaModificationText {
            get {
                return ResourceManager.GetString("DrawingAreaModificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layout name is already used. Override?.
        /// </summary>
        internal static string DuplicateLayoutNameText {
            get {
                return ResourceManager.GetString("DuplicateLayoutNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Layout Name.
        /// </summary>
        internal static string DuplicateLayoutNameTitle {
            get {
                return ResourceManager.GetString("DuplicateLayoutNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point.
        /// </summary>
        internal static string ExtractEndPointText {
            get {
                return ResourceManager.GetString("ExtractEndPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point.
        /// </summary>
        internal static string ExtractStartPointText {
            get {
                return ResourceManager.GetString("ExtractStartPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing paperformat.
        /// </summary>
        internal static string LoadPaperformatsDescription {
            get {
                return ResourceManager.GetString("LoadPaperformatsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading paperformats for printer.
        /// </summary>
        internal static string LoadPaperformatsErrorMessage {
            get {
                return ResourceManager.GetString("LoadPaperformatsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading paperformats.
        /// </summary>
        internal static string LoadPaperformatsErrorTitle {
            get {
                return ResourceManager.GetString("LoadPaperformatsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize loading.
        /// </summary>
        internal static string LoadPaperformatsInitialization {
            get {
                return ResourceManager.GetString("LoadPaperformatsInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading paperformats for printer.
        /// </summary>
        internal static string LoadPaperformatsText {
            get {
                return ResourceManager.GetString("LoadPaperformatsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Printer.
        /// </summary>
        internal static string LoadPaperformatsTitle {
            get {
                return ResourceManager.GetString("LoadPaperformatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drawing area detected..
        /// </summary>
        internal static string NoDrawingAreaMessage {
            get {
                return ResourceManager.GetString("NoDrawingAreaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no extract defined yet..
        /// </summary>
        internal static string NoExtractDefinedError {
            get {
                return ResourceManager.GetString("NoExtractDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no paperformats avaiblable for this printer..
        /// </summary>
        internal static string PaperformatListEmptyError {
            get {
                return ResourceManager.GetString("PaperformatListEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected paperformat does not fit the specified extract..
        /// </summary>
        internal static string PaperformatNotFitting {
            get {
                return ResourceManager.GetString("PaperformatNotFitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A printer with the specified name does not exist: .
        /// </summary>
        internal static string PrinterNameException {
            get {
                return ResourceManager.GetString("PrinterNameException", resourceCulture);
            }
        }
    }
}
